# 一、Numpy学习

## 1. ndarray的特性

### 多维性

In [2]:
import numpy as np
from pprint import pprint

In [3]:
arr = np.array([1,2,3,4,5]) # 创建1维数组
print(arr)
print(f'arr的维度：{arr.ndim}') # number of dimensions 表示当前数组的维度

[1 2 3 4 5]
arr的维度：1


In [4]:
arr = np.array(1)   # 创建0维数组
print(arr)
print(f'arr的维度：{arr.ndim}') # number of dimensions 表示当前数组的维度

1
arr的维度：0


In [5]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])   # 创建2维数组
print(arr)
print(f'arr的维度：{arr.ndim}') # number of dimensions 表示当前数组的维度

[[1 2 3 4 5]
 [1 2 3 4 5]]
arr的维度：2


### 同质性

In [6]:
arr = np.array([1,"尚硅谷"])   # 不同的数据类型会被强制转换成相同的数据类型
print(arr)
pprint(arr)

['1' '尚硅谷']
array(['1', '尚硅谷'], dtype='<U21')


In [7]:
arr = np.array([1,2.3])     # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.3]


## 2. ndarray的属性

In [8]:
arr = np.array(1)
print(arr)
print(f"数组的形状：{arr.shape}") # 0维数组的形状()
print(f"数组元素的个数：{arr.size}")
print(f"数组元素的数据类型：{arr.dtype}")

1
数组的形状：()
数组元素的个数：1
数组元素的数据类型：int64


In [9]:
arr = np.array([1,2.5,3,4])
print(arr)
print(f"数组的形状：{arr.shape}") # 1维数组的形状(列数,)
print(f"数组元素的个数：{arr.size}")
print(f"数组元素的数据类型：{arr.dtype}")
print(f"元素的转置：{arr.T}") # 1维数组不明显

[1.  2.5 3.  4. ]
数组的形状：(4,)
数组元素的个数：4
数组元素的数据类型：float64
元素的转置：[1.  2.5 3.  4. ]


In [10]:
arr = np.array([[1,2,"尚硅谷",4],[1,2,3,5]])
print(arr)
print(f"数组的形状：{arr.shape}") # 2维数组的形状(行数,列数)
print(f"数组元素的个数：{arr.size}")
print(f"数组元素的数据类型：{arr.dtype}")
print(f"元素的转置：\n{arr.T}")   # 2维数组比较明显

[['1' '2' '尚硅谷' '4']
 ['1' '2' '3' '5']]
数组的形状：(2, 4)
数组元素的个数：8
数组元素的数据类型：<U21
元素的转置：
[['1' '1']
 ['2' '2']
 ['尚硅谷' '3']
 ['4' '5']]


## 3. ndarray的创建

In [11]:
# 基础的创建方法
arr = np.array([1,2,3], dtype=np.float64) # 方法
print(arr.ndim) # 属性
print(arr)

1
[1. 2. 3.]


In [12]:
# copy
arr1 = np.copy(arr) # 元素跟参数里的数组相同，但是不是一个数组了
print(arr1)

[1. 2. 3.]


In [13]:
# 预定义形状
# 全0数组
arr = np.zeros((2,3))   # (行，列)
print(arr)
# 全1数组
arr = np.ones((3,3))
print(arr)
# 未初始化的数组
arr = np.empty((4,3))
print(arr)
# 固定值数组
arr = np.full((3,4),10)
print(arr)
# 特殊方法 np.zeros_like()  复制参数的形状，其中的值全为0 还有ones_like full_like empty_like 都有
arr1 = np.zeros_like(arr)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.29061074e-306 1.69119873e-306 1.78019082e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 1.34006200e-075]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
# 等差数列 1 2 3 4 5
arr = np.arange(1,10,2) # np.arange(start, end, step) 左闭右开
print(arr)

[1 3 5 7 9]


In [15]:
# 等间隔数列
arr = np.linspace(0,100,5,dtype=np.int64)   # start, end, space(间隔) 0  25  50  75  100
print(arr)

[  0  25  50  75 100]


In [16]:
# 对数间隔数列
arr = np.logspace(0,4,2,base=2) # start, end, 个数, base=数字(底数)默认为10
print(arr)

[ 1. 16.]


In [17]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其余数字为0
arr = np.eye(5,dtype=np.int64)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [18]:
# 对角矩阵：主对角线上为非0的数，其他的数字为0
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(3,4)   # (行，列)
print(arr)

[[0.3428293  0.95516328 0.98416125 0.11073609]
 [0.9977085  0.19101765 0.48205958 0.53286623]
 [0.2930016  0.69706038 0.31201626 0.51087673]]


In [20]:
# 生成指定范围区间的随机浮点数（均匀分布）
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[4.51724568 5.15543112 5.9520207 ]
 [4.55146992 5.77015913 5.95914293]]


In [21]:
# 生成指定范围区间的随机整数（均匀分布）
arr = np.random.randint(3,60,(2,3))
print(arr)

[[ 5 57 49]
 [52  8 59]]


In [22]:
# 生成随机数列（正态分布）（-3到3之间）
# 两边小，中间大
arr = np.random.randn(3,4)
print(arr)

[[ 1.24909625  2.06529268  1.5035228  -0.05879638]
 [-1.29569839  0.27148025  1.28151264  0.22083474]
 [-0.29577394 -0.73670361 -0.18424003  0.0517621 ]]


In [23]:
# 设置随机种子
np.random.seed(20)  # 设置种子之后每次生成的数字是一样的（时间戳）
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


### 4. ndarray的数据类型
布尔类型 bool

整数类型 int、uint

浮点数 float

复数 complex

In [24]:
# bool类型 true or false
arr = np.array([1,0,1,0,0],dtype=bool)
print(arr)

[ True False  True False False]


### 5.索引与切片

In [25]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0])
# 获取全部的元素
print(arr[:])
# 获取指定索引之间的切片
print(arr[2:5]) # [left,right)
# slice 切片方法
print(arr[slice(2,5)])  # start, end, step
# 布尔索引：通过布尔条件来获取元素
print(arr[arr>10])
print(arr[(arr>10) & (arr<70)])

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
17
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  8 99]
[17 63 17 99 27 14 76 59 26 75 76 62 78 84 58 95 33]
[17 63 17 27 14 59 26 62 58 33]


In [26]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)
# 切片第1行的内容
print(arr[0])
print(arr[0,:])
print(arr[1,2:5])
print(arr[1,slice(2,5)])
# 布尔索引（在二维数组中使用布尔索引返回的是一维数组）
print(arr[arr>50])
# 布尔索引 对指定行进行布尔索引
print(arr[2][arr[2]>50])

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]
[11  7 76 19  4 78 18 44]
[11  7 76 19  4 78 18 44]
[80 91 60]
[80 91 60]
[76 78 80 91 60 72 76 64 79 94 79 95 71 53]
[64 79 94]


### 5. ndarray的运算

In [27]:
# 算数运算
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a ** 2)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[1 4 9]


In [28]:
c = [1,2,3]
d = [4,5,6]
print(c+d)  # 列表相加是字符串拼接的概念

[1, 2, 3, 4, 5, 6]


In [29]:
# 数组和数组之间的算数运算
a = np.array([[1,3,4],[2,3,4],[4,5,6]])
b = np.array([[2,3,4],[6,7,8],[0,2,4]])
print(a+b)
print(a-b)
print(a*b)
print(a ** 2)
# 数组和标量之间的算数运算
print(a+2)

[[ 3  6  8]
 [ 8 10 12]
 [ 4  7 10]]
[[-1  0  0]
 [-4 -4 -4]
 [ 4  3  2]]
[[ 2  9 16]
 [12 21 32]
 [ 0 10 24]]
[[ 1  9 16]
 [ 4  9 16]
 [16 25 36]]
[[3 5 6]
 [4 5 6]
 [6 7 8]]


In [30]:
# 广播机制 —— 重点
# 同一维度：相同、或者行或列有一个是1行/列
a = np.array([1,2,3])   # 1*3
'''a
1 2 3
1 2 3
1 2 3
'''
b = np.array([[4],[5],[6]]) # 3*1
'''b
4 4 4
5 5 5
6 6 6
'''
print(a + b)

# 错误案例
a = np.array([1,2])   # 1*2
b = np.array([[4,5,6]]) # 1*3
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


ValueError: operands could not be broadcast together with shapes (2,) (1,3) 

In [ ]:
# 矩阵运算
a = np.array([[1,3,4],[2,3,4],[4,5,6]])
b = np.array([[2,3,4],[6,7,8],[0,2,4]])
print(a * b)    # 这个是数组相乘，对应位置相乘即可
print(a @ b)    # 这个是线性代数中矩阵的乘法运算

[[ 2  9 16]
 [12 21 32]
 [ 0 10 24]]
[[20 32 44]
 [22 35 48]
 [38 59 80]]


## numpy中的常用函数
### 1. 基本数学函数

In [ ]:
# 计算平方根，返回的结果是浮点数
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [ ]:
# 计算指数  e的多少次方 e^x
print(np.exp(9))

8103.083927575384


In [ ]:
# 计算自然对数 loge X 以e为底数
print(np.log(2.71))

0.9969486348916096


In [ ]:
# 计算三角函数
print(np.sin(-1))
print(np.cos(np.pi))

-0.8414709848078965
-1.0


In [ ]:
# 计算绝对值
arr = np.array([1,-2,3,-4])
print(np.abs(arr))

[1 2 3 4]


In [ ]:
# 计算a的b次幂
arr = np.array([1,-2,3,-4])
print(np.power(arr,2))

[ 1  4  9 16]


In [ ]:
# 四舍五入，银行家规则
print(np.round([3.2,4.5,8.1,9.6]))

[ 3.  4.  8. 10.]


In [ ]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr)) # 向上取整
print(np.floor(arr))    # 向下取整

[ 2. 26. 82.]
[ 1. 25. 81.]


In [ ]:
# 检测缺失值NaN
print(np.isnan([1, 2, 3, np.nan]))

[False False False  True]


### 2. 统计函数

求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差

In [32]:
arr = np.random.randint(1,20,8)
print(arr)

[11 11  2 19 18  9 19 11]


In [33]:
# 求和
print(np.sum(arr))

100


In [35]:
# 计算平均值    有两种mean 和 average，后者是加权平均值
print(np.mean(arr))

12.5


In [37]:
# 计算中位数    从小到大排序，然后选取中间的数字  
# 偶数：中间两个数的平均值  奇数：排序后中间的数值
print(np.median(arr))

11.0


In [42]:
# 计算标准差、方差      平均值相同，方差越小越稳定
print(np.var([1,2,100]))  # 方差
print(np.std([1,2,100]))  # 标准差

2156.2222222222217
46.435139950496776


In [44]:
# 计算最值  max和argmax     min和argmin
print(f"最大值：{np.max(arr)},最大值索引：{np.argmax(arr)}")
print(f"最小值：{np.min(arr)},最小值索引：{np.argmin(arr)}")

最大值：19,最大值索引：3
最小值：2,最小值索引：2


In [ ]:
# 分位数
# 中位数
print(np.median(arr))
# 分位数
np.random.seed(0)
arr = np.random.randint(1,20,4)
print(arr)
print(np.percentile(arr,25))
print(np.percentile(arr,80))
"""
------------------
1   4    13     16

首先计算一共有多少个区间(n - 1)     4 - 1 = 3
计算的是80%分位数 = 0.8 * 3 = 2.4
可以看到是在2 ~ 3 这个区间内 也就是 13 ~ 16之间
然后用(16 - 13) * 0.4 = 1.2
这里的0.4 是2.4的小数部分
然后再用 13 + 1.2 = 14.2
就能得到 80% 中位数了
"""

8.5
[13 16  1  4]
3.25
14.200000000000001


'\n------------------\n1   4    13     16\n\n首先计算一共有多少个区间(n - 1)     4 - 1 = 3\n计算的是80%分位数 = 0.8 * 3 = 2.4\n可以看到是在2 ~ 3 这个区间内 也就是 13 ~ 16之间\n然后用(16 - 13) * 0.4 = 1.2\n这里的0.4 是2.4的小数部分\n然后再用 13 + 1.2 = 14.2\n就能得到 80% 中位数了\n'

In [ ]:
# 累积和、累积积
arr = np.array([1,3,4,5,7])
print(np.sum(arr))
print(np.cumsum(arr))   # 前n项的和，例如arr[1]是第0项和第1项的和
print(np.cumprod(arr))  # 前n项的积

20
[ 1  4  8 13 20]
[  1   3  12  60 420]


比较函数：
    
    比较是否大于、小于、等于
    
    逻辑与、或、非
    
    检查数组中是否有一个True、是否所有的都为True、自定义条件

In [65]:
# 是否大于
print(np.greater([1,2,3,4,5],2))
# 是否小于
print(np.less([1,2,3,4,5],3))
# 是否等于
print(np.equal([1,3,4,5],3))
print(np.equal([1,3,4,5],[1,2,3,5]))    # 两个数组进行比较，按相应索引进行对比

[False False  True  True  True]
[ True  True False False False]
[False  True False False]
[ True False False  True]


In [68]:
# 逻辑与
print(np.logical_and([1,0],[1,1]))  # 逐元素逻辑与（对应位置比较）这里容易混淆，第一个元素和第一个元素进行逻辑运算
# 逻辑非
print(np.logical_not([1,0]))
# 逻辑或
print(np.logical_or([0,0],[0,1]))

[ True False]
[False  True]
[False  True]


In [70]:
# 检查元素是否至少有一个元素为True
print(np.any([0,0,0,0,0]))
# 检查元素是否全部元素为True
print(np.all([0,1,1,0,0]))

False
False


In [71]:
# 自定义条件
# print(np.where(条件,符合条件的,不符合条件的))
arr = np.array([1,2,3,4,5,6])
print(np.where(arr>3,arr,0))

[0 0 0 4 5 6]


In [84]:
score = np.random.randint(50,101,20)
print(score)
print(np.where(score>60,"及格","不及格"))

[91 92 81 51 51 89 91 85 88 61 96 68 77 50 64 85 62 92 70 61]
['及格' '及格' '及格' '不及格' '不及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '不及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [77]:
print(np.where(
    score<60,"不及格",np.where(
        score<80,"良好","优秀"
    )
))

['不及格' '不及格' '优秀' '优秀' '良好' '良好' '优秀' '良好' '优秀' '良好' '优秀' '不及格' '不及格' '优秀'
 '不及格' '优秀' '优秀' '良好' '良好' '不及格']


In [ ]:
 # np.select(条件,返回的结果,default="默认值")
 print(np.select([score<60,(score<=80)&(score>=60),score>80],["不及格","良好","优秀"],default="未知"))  # 实测缺一不可，不然就会报错

['优秀' '优秀' '优秀' '不及格' '不及格' '优秀' '优秀' '优秀' '优秀' '良好' '优秀' '良好' '良好' '不及格'
 '良好' '优秀' '良好' '优秀' '良好' '良好']


In [ ]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
# print(arr.sort())     直接改变原数组
# print(arr)
print(np.sort(arr))     # 不改变原数组，直接生成一个新的排序好的数组
print(np.argsort(arr))  # 不改变原数组，生成一个排序号的数组的索引 
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [95]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [97]:
 # 数组的拼接
 arr1 = np.array([1,2,3])
 arr2 = np.array([4,5,6])
 print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [103]:
# 数组的分割
print(np.split(arr,4))  # 这个份数必须要能被整除开的，如果无法整除会报错
print(np.split(arr,[6,12,18]))  # 切割位置的索引值，切了三刀分成四段

[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32), array([71, 89, 89, 13, 59], dtype=int32), array([66, 40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [104]:
# 调整数组的形状
print(np.reshape(arr,[4,5]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [111]:
"""
题目1：温度数据分析
某城市一周的最高气温℃为[28, 30, 29, 31, 32, 30, 29]。
- 计算平均气温，最高气温和最低气温
- 找出气温超过30℃的天数
"""
arr = np.array([28, 30, 29, 31, 32, 30, 29])
print(f"平均气温是：{np.round(np.mean(arr),1)}，最高气温是：{np.max(arr)}，最低气温是：{np.min(arr)}")
print(f"气温超过30℃的天数为：{np.size(arr[arr>30])}")

平均气温是：29.9，最高气温是：32，最低气温是：28
气温超过30℃的天数为：2


In [115]:
"""
题目 2：学生成绩统计
某班级 5 名学生的数学成绩为 [85,90,78,92,88]。
- 计算成绩的平均分、中位数和标准差。
- 将成绩转换为十分制（假设满分为 10）。
"""
arr = np.array([58,90,78,92,88])
print(f"平均分为：{np.mean(arr)}，中位数为：{np.median(arr)}，标准差为：{np.std(arr)}")
print(arr / 10)


平均分为：81.2，中位数为：88.0，标准差为：12.560254774486067
[5.8 9.  7.8 9.2 8.8]


In [122]:
"""
题目 3：矩阵运算
给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。
- 计算 A + B 和 A * B（逐元素乘法）。
- 计算 A 和 B 的矩阵乘法（点积）。
"""
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"A + B = \n{ A + B }\nA * B = \n{A * B}\n矩阵A与矩阵B相乘 = \n{A @ B}")

A + B = 
[[ 6  8]
 [10 12]]
A * B = 
[[ 5 12]
 [21 32]]
矩阵A与矩阵B相乘 = 
[[19 22]
 [43 50]]


In [129]:
"""
题目 4：随机数据生成

生成一个（3，4）的随机整数数组，范围 [0, 10)。

计算每列的最大值和每行的最小值。

将数组中的所有奇数替换为 -1。
"""
np.random.seed(0)
arr = np.random.randint(0,10,[3,4])
print(arr)
print(f"每列的最大值：{np.max(arr,axis=0)}")    # axis参数表示轴，0表示列，1表示行
print(f"每行的最小值：{np.min(arr,axis=1)}")    
print(np.where(arr%2==1,-1,arr))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值：[7 9 7 6]
每行的最小值：[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [137]:
"""
题目 5：数组变形

创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组。

计算每行的和与每列的平均值。

将数组展平为一维数组。
"""
arr = np.arange(1,13,1)
print(arr)
new_arr = np.reshape(arr,[3,4])
print(new_arr)
print(f"每行的和：{np.sum(new_arr,axis=1)}")
print(f"每列的平均值：{np.mean(new_arr,axis=0)}")
print(new_arr.reshape(12))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和：[10 26 42]
每列的平均值：[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
"""
生成一个（5，5）的随机数组，范围[0, 20]。

找出数组中大于 10 的元素。

将所有大于 10 的元素替换为 0。
"""
np.random.seed(0)
arr = np.random.randint(0,20,[5,5])
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [147]:
"""
题目 7：统计函数应用

某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。

计算销售额的总和、均值和方差。

找出销售额最高的月份和最低的月份。
"""
arr = np.array([120, 135, 110, 125, 130, 140])
print(f"销售额的总和：{np.sum(arr)}，均值：{np.mean(arr)}，方差：{arr.var()}")
print(f"销售额最高的月份：{np.argmax(arr)+1}，最低的月份：{arr.argmin()+1}")

销售额的总和：760，均值：126.66666666666667，方差：97.22222222222223
销售额最高的月份：6，最低的月份：3


In [156]:
"""
题目 8：数组拼接

给定 A = [1, 2, 3] 和 B = [4, 5, 6]。将 A 和 B 水平拼接为一个新数组。将 A 和 B 垂直拼接为一个新数组。
"""
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate((A,B))   # 水平拼接
print(C)
print(C.reshape(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [167]:
"""
题目 9：唯一值与排序

给定数组 [2, 1, 2, 3, 1, 4, 3]。

找出数组中的唯一值并排序。

计算每个唯一值出现的次数。
"""
arr = np.array([2, 1, 2, 3, 1, 4, 3])
unique,counts = np.unique(arr,return_counts=True)
print(unique,"\n",counts)

[1 2 3 4] 
 [2 2 2 1]


In [173]:
"""
题目：综合应用

某商店 5 天的销售额（万元）和成本（万元）如下：
销售额：[20, 25, 22, 30, 28]
成本：[15, 18, 16, 22, 20]

计算每天的利润（销售额 - 成本）。

计算利润的平均值和标准差。

找出利润最高的天数。
"""
smoney = np.array([20, 25, 22, 30, 28])
money = np.array([15, 18, 16, 22, 20])
lirun = smoney - money
print(f"每天的利润：{lirun}，利润的平均值：{lirun.mean()}，标准差：{lirun.std()}")
print(f"利润最高的天数为：{len(lirun[lirun==np.max(lirun)])}")



每天的利润：[5 7 6 8 8]，利润的平均值：6.8，标准差：1.16619037896906
利润最高的天数为：2
