# 一、Numpy学习

## 1. ndarray的特性

### 多维性

In [77]:
import numpy as np
from pprint import pprint

In [78]:
arr = np.array([1,2,3,4,5]) # 创建1维数组
print(arr)
print(f'arr的维度：{arr.ndim}') # number of dimensions 表示当前数组的维度

[1 2 3 4 5]
arr的维度：1


In [79]:
arr = np.array(1)   # 创建0维数组
print(arr)
print(f'arr的维度：{arr.ndim}') # number of dimensions 表示当前数组的维度

1
arr的维度：0


In [80]:
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])   # 创建2维数组
print(arr)
print(f'arr的维度：{arr.ndim}') # number of dimensions 表示当前数组的维度

[[1 2 3 4 5]
 [1 2 3 4 5]]
arr的维度：2


### 同质性

In [81]:
arr = np.array([1,"尚硅谷"])   # 不同的数据类型会被强制转换成相同的数据类型
print(arr)
pprint(arr)

['1' '尚硅谷']
array(['1', '尚硅谷'], dtype='<U21')


In [82]:
arr = np.array([1,2.3])     # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.3]


## 2. ndarray的属性

In [83]:
arr = np.array(1)
print(arr)
print(f"数组的形状：{arr.shape}") # 0维数组的形状()
print(f"数组元素的个数：{arr.size}")
print(f"数组元素的数据类型：{arr.dtype}")

1
数组的形状：()
数组元素的个数：1
数组元素的数据类型：int64


In [84]:
arr = np.array([1,2.5,3,4])
print(arr)
print(f"数组的形状：{arr.shape}") # 1维数组的形状(列数,)
print(f"数组元素的个数：{arr.size}")
print(f"数组元素的数据类型：{arr.dtype}")
print(f"元素的转置：{arr.T}") # 1维数组不明显

[1.  2.5 3.  4. ]
数组的形状：(4,)
数组元素的个数：4
数组元素的数据类型：float64
元素的转置：[1.  2.5 3.  4. ]


In [85]:
arr = np.array([[1,2,"尚硅谷",4],[1,2,3,5]])
print(arr)
print(f"数组的形状：{arr.shape}") # 2维数组的形状(行数,列数)
print(f"数组元素的个数：{arr.size}")
print(f"数组元素的数据类型：{arr.dtype}")
print(f"元素的转置：\n{arr.T}")   # 2维数组比较明显

[['1' '2' '尚硅谷' '4']
 ['1' '2' '3' '5']]
数组的形状：(2, 4)
数组元素的个数：8
数组元素的数据类型：<U21
元素的转置：
[['1' '1']
 ['2' '2']
 ['尚硅谷' '3']
 ['4' '5']]


## 3. ndarray的创建

In [86]:
# 基础的创建方法
arr = np.array([1,2,3], dtype=np.float64) # 方法
print(arr.ndim) # 属性
print(arr)

1
[1. 2. 3.]


In [87]:
# copy
arr1 = np.copy(arr) # 元素跟参数里的数组相同，但是不是一个数组了
print(arr1)

[1. 2. 3.]


In [92]:
# 预定义形状
# 全0数组
arr = np.zeros((2,3))   # (行，列)
print(arr)
# 全1数组
arr = np.ones((3,3))
print(arr)
# 未初始化的数组
arr = np.empty((4,3))
print(arr)
# 固定值数组
arr = np.full((3,4),10)
print(arr)
# 特殊方法 np.zeros_like()  复制参数的形状，其中的值全为0 还有ones_like full_like empty_like 都有
arr1 = np.zeros_like(arr)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [93]:
# 等差数列 1 2 3 4 5
arr = np.arange(1,10,2) # np.arange(start, end, step) 左闭右开
print(arr)

[1 3 5 7 9]


In [101]:
# 等间隔数列
arr = np.linspace(0,100,5,dtype=np.int64)   # start, end, space(间隔) 0  25  50  75  100
print(arr)

[  0  25  50  75 100]


In [106]:
# 对数间隔数列
arr = np.logspace(0,4,2,base=2) # start, end, 个数, base=数字(底数)默认为10
print(arr)

[ 1. 16.]


In [111]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其余数字为0
arr = np.eye(5,dtype=np.int64)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [113]:
# 对角矩阵：主对角线上为非0的数，其他的数字为0
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [116]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(3,4)   # (行，列)
print(arr)

[[0.00661833 0.37011963 0.12917097 0.61742194]
 [0.19672214 0.26215138 0.94590685 0.7900033 ]
 [0.99663093 0.31524793 0.26560313 0.09698915]]


In [118]:
# 生成指定范围区间的随机浮点数（均匀分布）
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[5.71677486 4.98575015 5.76597218]
 [4.31611097 3.06160159 3.88477462]]


In [121]:
# 生成指定范围区间的随机整数（均匀分布）
arr = np.random.randint(3,60,(2,3))
print(arr)

[[ 8 14 50]
 [18 16  3]]


In [124]:
# 生成随机数列（正态分布）（-3到3之间）
# 两边小，中间大
arr = np.random.randn(3,4)
print(arr)

[[ 0.19061796 -0.92742447  0.87741144 -2.62237662]
 [-0.91229312  0.53288515  1.07598312 -0.3644926 ]
 [-0.85192695 -0.03383849  0.68095045  0.22918486]]


In [128]:
# 设置随机种子
np.random.seed(20)  # 设置种子之后每次生成的数字是一样的（时间戳）
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


### 4. ndarray的数据类型
布尔类型 bool

整数类型 int、uint

浮点数 float

复数 complex

In [131]:
# bool类型 true or false
arr = np.array([1,0,1,0,0],dtype=bool)
print(arr)

[ True False  True False False]


### 5.索引与切片

In [152]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0])
# 获取全部的元素
print(arr[:])
# 获取指定索引之间的切片
print(arr[2:5]) # [left,right)
# slice 切片方法
print(arr[slice(2,5)])  # start, end, step
# 布尔索引：通过布尔条件来获取元素
print(arr[arr>10])
print(arr[(arr>10) & (arr<70)])

[97 77 79 96 55 82 74 28 40 88 10 15 32 57 57 59 80 28 51 75]
97
[97 77 79 96 55 82 74 28 40 88 10 15 32 57 57 59 80 28 51 75]
[79 96 55]
[79 96 55]
[97 77 79 96 55 82 74 28 40 88 15 32 57 57 59 80 28 51 75]
[55 28 40 15 32 57 57 59 28 51]


In [173]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)
# 切片第1行的内容
print(arr[0])
print(arr[0,:])
print(arr[1,2:5])
print(arr[1,slice(2,5)])
# 布尔索引（在二维数组中使用布尔索引返回的是一维数组）
print(arr[arr>50])
# 布尔索引 对指定行进行布尔索引
print(arr[2][arr[2]>50])

[[ 2 89  6 92 64 96 40 96]
 [50 25 94 54 35 81 85 72]
 [85 43  9 92 80  8 94 50]
 [30 18 16 45 69 77 37 64]]
[ 2 89  6 92 64 96 40 96]
[ 2 89  6 92 64 96 40 96]
[94 54 35]
[94 54 35]
[89 92 64 96 96 94 54 81 85 72 85 92 80 94 69 77 64]
[85 92 80 94]


### 5. ndarray的运算

In [179]:
# 算数运算
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a ** 2)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[1 4 9]


In [178]:
c = [1,2,3]
d = [4,5,6]
print(c+d)  # 列表相加是字符串拼接的概念

[1, 2, 3, 4, 5, 6]


In [182]:
# 数组和数组之间的算数运算
a = np.array([[1,3,4],[2,3,4],[4,5,6]])
b = np.array([[2,3,4],[6,7,8],[0,2,4]])
print(a+b)
print(a-b)
print(a*b)
print(a ** 2)
# 数组和标量之间的算数运算
print(a+2)

[[ 3  6  8]
 [ 8 10 12]
 [ 4  7 10]]
[[-1  0  0]
 [-4 -4 -4]
 [ 4  3  2]]
[[ 2  9 16]
 [12 21 32]
 [ 0 10 24]]
[[ 1  9 16]
 [ 4  9 16]
 [16 25 36]]
[[3 5 6]
 [4 5 6]
 [6 7 8]]


In [186]:
# 广播机制 —— 重点
# 同一维度：相同、或者行或列有一个是1行/列
a = np.array([1,2,3])   # 1*3
'''a
1 2 3
1 2 3
1 2 3
'''
b = np.array([[4],[5],[6]]) # 3*1
'''b
4 4 4
5 5 5
6 6 6
'''
print(a + b)

# 错误案例
a = np.array([1,2])   # 1*2
b = np.array([[4,5,6]]) # 1*3
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


ValueError: operands could not be broadcast together with shapes (2,) (1,3) 

In [188]:
# 矩阵运算
a = np.array([[1,3,4],[2,3,4],[4,5,6]])
b = np.array([[2,3,4],[6,7,8],[0,2,4]])
print(a * b)    # 这个是数组相乘，对应位置相乘即可
print(a @ b)    # 这个是线性代数中矩阵的乘法运算

[[ 2  9 16]
 [12 21 32]
 [ 0 10 24]]
[[20 32 44]
 [22 35 48]
 [38 59 80]]


## numpy中的常用函数
### 1. 基本数学函数

In [193]:
# 计算平方根，返回的结果是浮点数
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [197]:
# 计算指数  e的多少次方 e^x
print(np.exp(9))

8103.083927575384


In [198]:
# 计算自然对数 loge X 以e为底数
print(np.log(2.71))

0.9969486348916096


In [201]:
# 计算三角函数
print(np.sin(-1))
print(np.cos(np.pi))

-0.8414709848078965
-1.0


In [202]:
# 计算绝对值
arr = np.array([1,-2,3,-4])
print(np.abs(arr))

[1 2 3 4]


In [204]:
# 计算a的b次幂
arr = np.array([1,-2,3,-4])
print(np.power(arr,2))

[ 1  4  9 16]


In [206]:
# 四舍五入，银行家规则
print(np.round([3.2,4.5,8.1,9.6]))

[ 3.  4.  8. 10.]


In [208]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr)) # 向上取整
print(np.floor(arr))    # 向下取整

[ 2. 26. 82.]
[ 1. 25. 81.]


In [211]:
# 检测缺失值NaN
print(np.isnan([1, 2, 3, np.nan]))

[False False False  True]
